### ISSUE TITLE
crashing on FirmwareUpgradeManager start()

### ISSUE THREAD

**Issue by katinas15** [JuulLabs-OSS/mcumgr-android#82]
When I call the start() function the app crashes. Errors are not really clear, maybe someone can help me out. I select a file, read it as bytes, then start(). My firmware file has .bin file extension (if that makes any difference). I don't think it is a problem with my phone, since I can update firmware using nRF Connect, but my code crashes. Thank you.

<details>
  <summary> MyCode
  </summary>

```
public class FlashActivity extends AppCompatActivity {
    TextView fileText;
    private Uri fileUri;
    private String filePath;
    BluetoothDevice bluetoothDevice;
    File file;
    byte[] bytes;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);


        final Intent intent = getIntent();
        bluetoothDevice = (BluetoothDevice) intent.getExtras().get("Device");

        setContentView(R.layout.activity_flash);
    }

    public void selectFile(View v){
        Intent chooseFile = new Intent(Intent.ACTION_GET_CONTENT);
        chooseFile.setType("*/*");
        chooseFile = Intent.createChooser(chooseFile, "Choose a file");
        startActivityForResult(chooseFile, 1);
    }





    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case 1:
                if (resultCode == -1) {


                    fileUri = data.getData();
                    filePath = fileUri.getPath();
                    file = new File(fileUri.getPath());
                    try {

                        InputStream ips = getContentResolver().openInputStream(fileUri);

                        bytes = new byte[ips.available()];
                        ips.read(bytes, 0, bytes.length);

                        fileText = findViewById(R.id.fileText);
                        fileText.setText(filePath);
                    } catch (FileNotFoundException e) {
                        e.printStackTrace();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                    break;
                }
        }
    }

    public void clickFlash(View v) throws McuMgrException, IOException {
        McuMgrTransport transport = new McuMgrBleTransport(this, bluetoothDevice);
        FirmwareUpgradeManager dfuManager = new FirmwareUpgradeManager(transport);

        dfuManager.start(bytes);
    }


}
```
</details>

<details>
  <summary>Logs</summary>

```
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
W/System: A resource failed to call close. 
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.safety_app, PID: 32495
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:414)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409)
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.BootstrapMethodError: Exception from call site #67 bootstrap method
        at no.nordicsemi.android.ble.Request.notifyStarted(Request.java:1175)
        at no.nordicsemi.android.ble.TimeoutableRequest.notifyStarted(TimeoutableRequest.java:195)
        at no.nordicsemi.android.ble.BleManagerHandler.nextRequest(BleManagerHandler.java:2857)
        at no.nordicsemi.android.ble.BleManagerHandler.enqueue(BleManagerHandler.java:1161)
        at no.nordicsemi.android.ble.Request.enqueue(Request.java:1166)
        at no.nordicsemi.android.ble.TimeoutableRequest.enqueue(TimeoutableRequest.java:76)
        at io.runtime.mcumgr.ble.McuMgrBleTransport.send(McuMgrBleTransport.java:380)
        at io.runtime.mcumgr.McuManager.send(McuManager.java:259)
        at io.runtime.mcumgr.McuManager.send(McuManager.java:216)
        at io.runtime.mcumgr.McuManager.send(McuManager.java:168)
        at io.runtime.mcumgr.managers.ImageManager.list(ImageManager.java:88)
        at io.runtime.mcumgr.dfu.FirmwareUpgradeManager.validate(FirmwareUpgradeManager.java:337)
        at io.runtime.mcumgr.dfu.FirmwareUpgradeManager.start(FirmwareUpgradeManager.java:275)
        at com.example.safety_app.FlashActivity.clickFlash(FlashActivity.java:101)
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409) 
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at no.nordicsemi.android.ble.Request.notifyStarted(Request.java:1175) 
        at no.nordicsemi.android.ble.TimeoutableRequest.notifyStarted(TimeoutableRequest.java:195) 
        at no.nordicsemi.android.ble.BleManagerHandler.nextRequest(BleManagerHandler.java:2857) 
        at no.nordicsemi.android.ble.BleManagerHandler.enqueue(BleManagerHandler.java:1161) 
        at no.nordicsemi.android.ble.Request.enqueue(Request.java:1166) 
        at no.nordicsemi.android.ble.TimeoutableRequest.enqueue(TimeoutableRequest.java:76) 
        at io.runtime.mcumgr.ble.McuMgrBleTransport.send(McuMgrBleTransport.java:380) 
        at io.runtime.mcumgr.McuManager.send(McuManager.java:259) 
        at io.runtime.mcumgr.McuManager.send(McuManager.java:216) 
        at io.runtime.mcumgr.McuManager.send(McuManager.java:168) 
        at io.runtime.mcumgr.managers.ImageManager.list(ImageManager.java:88) 
        at io.runtime.mcumgr.dfu.FirmwareUpgradeManager.validate(FirmwareUpgradeManager.java:337) 
        at io.runtime.mcumgr.dfu.FirmwareUpgradeManager.start(FirmwareUpgradeManager.java:275) 
        at com.example.safety_app.FlashActivity.clickFlash(FlashActivity.java:101) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409) 
        at android.view.View.performClick(View.java:6608) 
        at android.view.View.performClickInternal(View.java:6585) 
        at android.view.View.access$3100(View.java:785) 
        at android.view.View$PerformClick.run(View.java:25921) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
```
</details>

**Comment by katinas15** [comment]
Apparently adding a few lines to build.gradle fixes the issue:

`    
android {
   compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
}
`

closing the issue.

**Comment by bgiori** [comment]
@ katinas15

Sorry for not getting to this. Glad you figured it out!
